### PR TITLE
Feature/ksp 191

### PR DESCRIPTION
**Pull request by mwerle**
Recompiled for KSP1.9.1, but also made the various project files nicer for others to contribute using my "standard" layout.

Basically, the configuration should work "out of the box" for you as the original author.

Anybody making their own build only needs to copy "AnimatedDecouplers.User.props.template" to "AnimatedDecouplers.User.props" and edit according to their setup.

Take it or leave it :)

### CODE REVIEW

**Comment by mwerle** [comment]
PS. I was about to add scripts to automatically build a release etc, but then I saw a note saying you were working on a new version..  let me know if you'd like them anyway.

**Comment by Starwaster** [comment]
I'd already had a local build for KSP 1.9 previously and as for the templates I'd have to look those over and see if I want to do that.

**Comment by Starwaster** [comment]
* Ok so just over a year later, might still fold those templates in but a few issues in this if you're still around and feel like updating the PR.

dll and version changes need to be removed as those changes are outdated and the mod is updated.
csproj has conflicts now (due to changes)
most important though are that the license and readme cant be removed from the mod's folder in Gamedata, especially license which is required to be in the downloaded mod folder.

**Comment by mwerle** [comment]
Sorry, I thought I had replied to your earlier comment. Really busy with work and other stuff right now so not much time for KSP.. but I would like to revisit this at some point if you're still interested.

**Comment by Starwaster** [comment]
Sure when you have time to revisit it, let me know. Unless KSP2 drops and we all switch over

**Pull request closed without merging**
