### PR TITLE
1.0.5 fix.

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
One more check to avoid NullReferenceExceptions and breakage.  Tests OK in 1.0.5 with Modular Rocket Systems shroud.

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
Tests OK with SDHI BPC.  (No idea if it fixes the not-animating-before-decoupling of the avionics ring that others have seen.)

**Comment by Starwaster** [comment]
FYI, if you see something like '(object)anim == null)' please don't change that :)

**Comment by Kerbas-ad-astra** [comment]
Sorry about that - can't even think of why I removed that keyword in the first place.

**Comment by gparent** [comment]
@Starwaster Why must anim be casted to object before being compared to null? I was looking at the code of this mod and now I can't find it documented anywhere.

**Comment by Starwaster** [comment]
It's supposed to be more efficient than (anim == null) (performance wise)

**Pull request merged**
